### ISSUE TITLE
ESPN no longer an option

### ISSUE THREAD

**Issue by Chris-May** [realpython/list-of-python-api-wrappers#11]
ESPN has shut down their public API.
`As part of that evolution, we have made the difficult decision to discontinue our public APIs`
`Developers utilizing the ESPN API with a public API key may continue to do so until Monday, December 8, 2014, at which point the keys will no longer be active.`
- http://espn.go.com/static/apis/devcenter/blog/read/publicretirement.html

**Comment by mjhea0** [comment]
Bummer. Want to submit a PR to remove? :)

**Comment by Chris-May** [comment]
Oh yeah! I'd be happy to.
