### ISSUE TITLE
Spotify API's out of date 

### ISSUE THREAD

**Issue by Dtphelan1** [realpython/list-of-python-api-wrappers#64]
Hey Devs! 

Just wanted to let you know that your listed Spotify API is out of date. Specifically, the API was dependent on a library called 'libspotify' which is no longer maintained; so by transitive property... you get the picture. 

I can't attest to its effectiveness but I have seen the library [spotipy](https://github.com/plamere/spotipy) referenced as a powerful wrapper around the spotify API. Might be a good replacement.

Thanks for the great resource! 
- Dylan

**Comment by mjhea0** [comment]
Thanks! Want to issue a PR removing the current Spotify API and adding in https://github.com/plamere/spotipy?

**Comment by Dtphelan1** [comment]
Can do!

**Comment by mjhea0** [comment]
https://github.com/realpython/list-of-python-api-wrappers/pull/65
